apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- deployment.yaml
- service.yaml

helmCharts:
- name: mysql
  releaseName: mysql
  repo: https://charts.helm.sh/stable/
  namespace: default
  valuesInLine:
    mysqlUser: ledger
    mysqlPassword: ledger
    mysqlDatabase: ledger