
apiVersion: v1
kind: Service
metadata:
  name: ledger-svc-headless
  namespace: default
  labels:
    app.kubernetes.io/name: ledger
    app.kubernetes.io/instance: ledger-svc-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
    - port: 4000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ledger
    app.kubernetes.io/instance: ledger-node